INSERT INTO `countries` (`id`, `name`, `iso`, `iso3`, `currency`, `currency_code`, `currency_symbol`, `phonecode`, `min`, `max`, `created_at`, `updated_at`) VALUES
(1, 'Afghanistan', 'AF', 'AFG', 'Afghan afg', 'AFN', '؋', '93', '9', '9', NULL, NULL),
(2, 'Albania', 'AL', 'ALB', 'Albanian l', 'ALL', 'L', '355', '9', '9', NULL, NULL),
(3, 'Algeria', 'DZ', 'DZA', 'Algerian d', 'DZD', 'د.ج', '213', '9', '9', NULL, NULL),
(4, 'Andorra', 'AD', 'AND', 'Euro', 'EUR', '€', '376', '6', '6', NULL, NULL),
(5, 'Angola', 'AO', 'AGO', 'Angolan kw', 'AOA', 'Kz', '244', '9', '9', NULL, NULL),
(6, 'Antigua and Barbuda', 'AG', 'ATG', 'East Carib', 'XCD', '$', '1-268', '10', '10', NULL, NULL),
(7, 'Argentina', 'AR', 'ARG', 'Argentine ', 'ARS', '$', '54', '10', '10', NULL, NULL),
(8, 'Armenia', 'AM', 'ARM', 'Armenian d', 'AMD', '֏', '374', '8', '8', NULL, NULL),
(9, 'Australia', 'AU', 'AUS', 'Australian', 'AUD', '$', '61', '9', '9', NULL, NULL),
(10, 'Austria', 'AT', 'AUT', 'Euro', 'EUR', '€', '43', '10', '10', NULL, NULL),
(11, 'Azerbaijan', 'AZ', 'AZE', 'Azerbaijan', 'AZN', '₼', '994', '9', '9', NULL, NULL),
(12, 'Bahamas', 'BS', 'BHS', 'Bahamian d', 'BSD', '$', '1-242', '10', '10', NULL, NULL),
(13, 'Bahrain', 'BH', 'BHR', 'Bahraini d', 'BHD', '.د.ب', '973', '8', '8', NULL, NULL),
(14, 'Bangladesh', 'BD', 'BGD', 'Bangladesh', 'BDT', '৳', '880', '10', '12', NULL, NULL),
(15, 'Barbados', 'BB', 'BRB', 'Barbadian ', 'BBD', '$', '1-246', '10', '10', NULL, NULL),
(16, 'Belarus', 'BY', 'BLR', 'Belarusian', 'BYN', 'Br', '375', '9', '9', NULL, NULL),
(17, 'Belgium', 'BE', 'BEL', 'Euro', 'EUR', '€', '32', '9', '9', NULL, NULL),
(18, 'Belize', 'BZ', 'BLZ', 'Belize dol', 'BZD', '$', '501', '7', '7', NULL, NULL),
(19, 'Benin', 'BJ', 'BEN', 'West Afric', 'XOF', 'Fr', '229', '9', '9', NULL, NULL),
(20, 'Bhutan', 'BT', 'BTN', 'Bhutanese ', 'BTN', 'Nu.', '975', '9', '9', NULL, NULL),
(21, 'Bolivia', 'BO', 'BOL', 'Bolivian b', 'BOB', 'Bs.', '591', '8', '8', NULL, NULL),
(22, 'Bosnia and Herzegovina', 'BA', 'BIH', 'Convertibl', 'BAM', 'KM', '387', '8', '8', NULL, NULL),
(23, 'Botswana', 'BW', 'BWA', 'Botswana p', 'BWP', 'P', '267', '8', '8', NULL, NULL),
(24, 'Brazil', 'BR', 'BRA', 'Brazilian ', 'BRL', 'R$', '55', '11', '11', NULL, NULL),
(25, 'Brunei', 'BN', 'BRN', 'Brunei dol', 'BND', '$', '673', '8', '8', NULL, NULL),
(26, 'Bulgaria', 'BG', 'BGR', 'Bulgarian ', 'BGN', 'лв', '359', '9', '10', NULL, NULL),
(27, 'Burkina Faso', 'BF', 'BFA', 'West Afric', 'XOF', 'Fr', '226', '8', '8', NULL, NULL),
(28, 'Burundi', 'BI', 'BDI', 'Burundian ', 'BIF', 'Fr', '257', '8', '8', NULL, NULL),
(29, 'Cabo Verde', 'CV', 'CPV', 'Cape Verde', 'CVE', '$', '238', '7', '7', NULL, NULL),
(30, 'Cambodia', 'KH', 'KHM', 'Cambodian ', 'KHR', '៛', '855', '9', '9', NULL, NULL),
(31, 'Cameroon', 'CM', 'CMR', 'Central Af', 'XAF', 'Fr', '237', '8', '8', NULL, NULL),
(32, 'Canada', 'CA', 'CAN', 'Canadian d', 'CAD', '$', '1', '10', '12', NULL, NULL),
(33, 'Central African Republic', 'CF', 'CAF', 'Central Af', 'XAF', 'Fr', '236', '8', '8', NULL, NULL),
(34, 'Chad', 'TD', 'TCD', 'Central Af', 'XAF', 'Fr', '235', '8', '8', NULL, NULL),
(35, 'Chile', 'CL', 'CHL', 'Chilean pe', 'CLP', '$', '56', '10', '10', NULL, NULL),
(36, 'China', 'CN', 'CHN', 'Chinese yu', 'CNY', '¥', '86', '11', '12', NULL, NULL),
(37, 'Colombia', 'CO', 'COL', 'Colombian ', 'COP', '$', '57', '10', '10', NULL, NULL),
(38, 'Comoros', 'KM', 'COM', 'Comorian f', 'KMF', 'Fr', '269', '8', '8', NULL, NULL),
(39, 'Congo, Democratic Republic of the', 'CD', 'COD', 'Congolese ', 'CDF', 'Fr', '243', '9', '9', NULL, NULL),
(40, 'Congo, Republic of the', 'CG', 'COG', 'Central Af', 'XAF', 'Fr', '242', '9', '9', NULL, NULL),
(41, 'Costa Rica', 'CR', 'CRI', 'Costa Rica', 'CRC', '₡', '506', '8', '8', NULL, NULL),
(42, 'Croatia', 'HR', 'HRV', 'Croatian k', 'HRK', 'kn', '385', '9', '9', NULL, NULL),
(43, 'Cuba', 'CU', 'CUB', 'Cuban peso', 'CUP', '$', '53', '8', '12', NULL, NULL),
(44, 'Cyprus', 'CY', 'CYP', 'Euro', 'EUR', '€', '357', '8', '8', NULL, NULL),
(45, 'Czech Republic', 'CZ', 'CZE', 'Czech koru', 'CZK', 'Kč', '420', '9', '9', NULL, NULL),
(46, 'Denmark', 'DK', 'DNK', 'Danish kro', 'DKK', 'kr', '45', '8', '8', NULL, NULL),
(47, 'Djibouti', 'DJ', 'DJI', 'Djiboutian', 'DJF', 'Fr', '253', '8', '8', NULL, NULL),
(48, 'Dominica', 'DM', 'DMA', 'East Carib', 'XCD', '$', '1-767', '10', '10', NULL, NULL),
(49, 'Dominican Republic', 'DO', 'DOM', 'Dominican ', 'DOP', '$', '1-809, 1-829, 1-849', '10', '12', NULL, NULL),
(50, 'East Timor (Timor-Leste)', 'TL', 'TLS', 'United Sta', 'USD', '$', '670', '8', '8', NULL, NULL),
(51, 'Ecuador', 'EC', 'ECU', 'United Sta', 'USD', '$', '593', '10', '10', NULL, NULL),
(52, 'Egypt', 'EG', 'EGY', 'Egyptian p', 'EGP', '£', '20', '10', '12', NULL, NULL),
(53, 'El Salvador', 'SV', 'SLV', 'United Sta', 'USD', '$', '503', '8', '12', NULL, NULL),
(54, 'Equatorial Guinea', 'GQ', 'GNQ', 'Central Af', 'XAF', 'Fr', '240', '8', '8', NULL, NULL),
(55, 'Eritrea', 'ER', 'ERI', 'Eritrean n', 'ERN', 'Nfk', '291', '8', '8', NULL, NULL),
(56, 'Estonia', 'EE', 'EST', 'Euro', 'EUR', '€', '372', '8', '8', NULL, NULL),
(57, 'Ethiopia', 'ET', 'ETH', 'Ethiopian ', 'ETB', 'Br', '251', '9', '9', NULL, NULL),
(58, 'Fiji', 'FJ', 'FJI', 'Fijian dol', 'FJD', '$', '679', '8', '8', NULL, NULL),
(59, 'Finland', 'FI', 'FIN', 'Euro', 'EUR', '€', '358', '9', '9', NULL, NULL),
(60, 'France', 'FR', 'FRA', 'Euro', 'EUR', '€', '33', '9', '9', NULL, NULL),
(61, 'Gabon', 'GA', 'GAB', 'Central Af', 'XAF', 'Fr', '241', '8', '8', NULL, NULL),
(62, 'Gambia', 'GM', 'GMB', 'Gambian da', 'GMD', 'D', '220', '8', '8', NULL, NULL),
(63, 'Georgia', 'GE', 'GEO', 'Georgian l', 'GEL', '₾', '995', '9', '9', NULL, NULL),
(64, 'Germany', 'DE', 'DEU', 'Euro', 'EUR', '€', '49', '10', '10', NULL, NULL),
(65, 'Ghana', 'GH', 'GHA', 'Ghanaian c', 'GHS', '₵', '233', '9', '10', NULL, NULL),
(66, 'Greece', 'GR', 'GRC', 'Euro', 'EUR', '€', '30', '10', '10', NULL, NULL),
(67, 'Grenada', 'GD', 'GRD', 'East Carib', 'XCD', '$', '1-473', '10', '10', NULL, NULL),
(68, 'Guatemala', 'GT', 'GTM', 'Guatemalan', 'GTQ', 'Q', '502', '8', '8', NULL, NULL),
(69, 'Guinea', 'GN', 'GIN', 'Guinean fr', 'GNF', 'Fr', '224', '8', '8', NULL, NULL),
(70, 'Guinea-Bissau', 'GW', 'GNB', 'West Afric', 'XOF', 'Fr', '245', '8', '8', NULL, NULL),
(71, 'Guyana', 'GY', 'GUY', 'Guyanese d', 'GYD', '$', '592', '9', '9', NULL, NULL),
(72, 'Haiti', 'HT', 'HTI', 'Haitian go', 'HTG', 'G', '509', '8', '8', NULL, NULL),
(73, 'Honduras', 'HN', 'HND', 'Honduran l', 'HNL', 'L', '504', '8', '8', NULL, NULL),
(74, 'Hungary', 'HU', 'HUN', 'Hungarian ', 'HUF', 'Ft', '36', '9', '10', NULL, NULL),
(75, 'Iceland', 'IS', 'ISL', 'Icelandic ', 'ISK', 'kr', '354', '7', '9', NULL, NULL),
(76, 'India', 'IN', 'IND', 'Indian rup', 'INR', '₹', '91', '10', '12', NULL, NULL),
(77, 'Indonesia', 'ID', 'IDN', 'Indonesian', 'IDR', 'Rp', '62', '9', '13', NULL, NULL),
(78, 'Iran', 'IR', 'IRN', 'Iranian ri', 'IRR', '﷼', '98', '10', '12', NULL, NULL),
(79, 'Iraq', 'IQ', 'IRQ', 'Iraqi dina', 'IQD', 'ع.د', '964', '8', '8', NULL, NULL),
(80, 'Ireland', 'IE', 'IRL', 'Euro', 'EUR', '€', '353', '9', '9', NULL, NULL),
(81, 'Israel', 'IL', 'ISR', 'Israeli ne', 'ILS', '₪', '972', '9', '10', NULL, NULL),
(82, 'Italy', 'IT', 'ITA', 'Euro', 'EUR', '€', '39', '10', '11', NULL, NULL),
(83, 'Jamaica', 'JM', 'JAM', 'Jamaican d', 'JMD', '$', '1-876', '10', '10', NULL, NULL),
(84, 'Japan', 'JP', 'JPN', 'Japanese y', 'JPY', '¥', '81', '10', '12', NULL, NULL),
(85, 'Jordan', 'JO', 'JOR', 'Jordanian ', 'JOD', 'د.ا', '962', '9', '9', NULL, NULL),
(86, 'Kazakhstan', 'KZ', 'KAZ', 'Kazakhstan', 'KZT', '₸', '7', '10', '12', NULL, NULL),
(87, 'Kenya', 'KE', 'KEN', 'Kenyan shi', 'KES', 'Sh', '254', '10', '12', NULL, NULL),
(88, 'Kiribati', 'KI', 'KIR', 'Australian', 'AUD', '$', '686', '8', '8', NULL, NULL),
(89, 'Korea, North', 'KP', 'PRK', 'North Kore', 'KPW', '₩', '850', '9', '9', NULL, NULL),
(90, 'Korea, South', 'KR', 'KOR', 'South Kore', 'KRW', '₩', '82', '10', '12', NULL, NULL),
(91, 'Kosovo', 'XK', 'XKX', 'Euro', 'EUR', '€', '383', '8', '8', NULL, NULL),
(92, 'Kuwait', 'KW', 'KWT', 'Kuwaiti di', 'KWD', 'د.ك', '965', '8', '8', NULL, NULL),
(93, 'Kyrgyzstan', 'KG', 'KGZ', 'Kyrgyzstan', 'KGS', 'сом', '996', '9', '9', NULL, NULL),
(94, 'Laos', 'LA', 'LAO', 'Lao kip', 'LAK', '₭', '856', '9', '9', NULL, NULL),
(95, 'Latvia', 'LV', 'LVA', 'Euro', 'EUR', '€', '371', '8', '8', NULL, NULL),
(96, 'Lebanon', 'LB', 'LBN', 'Lebanese p', 'LBP', 'ل.ل', '961', '8', '8', NULL, NULL),
(97, 'Lesotho', 'LS', 'LSO', 'Lesotho lo', 'LSL', 'L', '266', '8', '8', NULL, NULL),
(98, 'Liberia', 'LR', 'LBR', 'Liberian d', 'LRD', '$', '231', '8', '8', NULL, NULL),
(99, 'Libya', 'LY', 'LBY', 'Libyan din', 'LYD', 'ل.د', '218', '9', '9', NULL, NULL),
(100, 'Liechtenstein', 'LI', 'LIE', 'Swiss fran', 'CHF', 'Fr', '423', '9', '9', NULL, NULL),
(101, 'Lithuania', 'LT', 'LTU', 'Euro', 'EUR', '€', '370', '8', '8', NULL, NULL),
(102, 'Luxembourg', 'LU', 'LUX', 'Euro', 'EUR', '€', '352', '9', '9', NULL, NULL),
(103, 'Madagascar', 'MG', 'MDG', 'Malagasy a', 'MGA', 'Ar', '261', '8', '8', NULL, NULL),
(104, 'Malawi', 'MW', 'MWI', 'Malawian k', 'MWK', 'MK', '265', '9', '9', NULL, NULL),
(105, 'Malaysia', 'MY', 'MYS', 'Malaysian ', 'MYR', 'RM', '60', '10', '11', NULL, NULL),
(106, 'Maldives', 'MV', 'MDV', 'Maldivian ', 'MVR', 'Rf', '960', '8', '8', NULL, NULL),
(107, 'Mali', 'ML', 'MLI', 'West Afric', 'XOF', 'Fr', '223', '8', '8', NULL, NULL),
(108, 'Malta', 'MT', 'MLT', 'Euro', 'EUR', '€', '356', '8', '8', NULL, NULL),
(109, 'Marshall Islands', 'MH', 'MHL', 'United Sta', 'USD', '$', '692', '8', '8', NULL, NULL),
(110, 'Mauritania', 'MR', 'MRT', 'Mauritania', 'MRU', 'UM', '222', '8', '8', NULL, NULL),
(111, 'Mauritius', 'MU', 'MUS', 'Mauritian ', 'MUR', '₨', '230', '8', '8', NULL, NULL),
(112, 'Mexico', 'MX', 'MEX', 'Mexican pe', 'MXN', '$', '52', '10', '12', NULL, NULL),
(113, 'Micronesia, Federated States of', 'FM', 'FSM', 'United Sta', 'USD', '$', '691', '8', '8', NULL, NULL),
(114, 'Moldova', 'MD', 'MDA', 'Moldovan l', 'MDL', 'L', '373', '8', '8', NULL, NULL),
(115, 'Monaco', 'MC', 'MCO', 'Euro', 'EUR', '€', '377', '8', '8', NULL, NULL),
(116, 'Mongolia', 'MN', 'MNG', 'Mongolian ', 'MNT', '₮', '976', '8', '9', NULL, NULL),
(117, 'Montserrat', 'MS', 'MSR', 'East Carib', 'XCD', '$', '1-664', '10', '10', NULL, NULL),
(118, 'Morocco', 'MA', 'MAR', 'Moroccan d', 'MAD', 'د.م.', '212', '9', '9', NULL, NULL),
(119, 'Mozambique', 'MZ', 'MOZ', 'Mozambican', 'MZN', 'MT', '258', '9', '9', NULL, NULL),
(120, 'Myanmar (Burma)', 'MM', 'MMR', 'Burmese ky', 'MMK', 'Ks', '95', '10', '10', NULL, NULL),
(121, 'Namibia', 'NA', 'NAM', 'Namibian d', 'NAD', '$', '264', '10', '12', NULL, NULL),
(122, 'Nauru', 'NR', 'NRU', 'Australian', 'AUD', '$', '674', '8', '8', NULL, NULL),
(123, 'Nepal', 'NP', 'NPL', 'Nepalese r', 'NPR', '₨', '977', '10', '12', NULL, NULL),
(124, 'Netherlands', 'NL', 'NLD', 'Euro', 'EUR', '€', '31', '10', '10', NULL, NULL),
(125, 'New Zealand', 'NZ', 'NZL', 'New Zealan', 'NZD', '$', '64', '10', '11', NULL, NULL),
(126, 'Nicaragua', 'NI', 'NIC', 'Nicaraguan', 'NIO', 'C$', '505', '8', '8', NULL, NULL),
(127, 'Niger', 'NE', 'NER', 'West Afric', 'XOF', 'Fr', '227', '8', '8', NULL, NULL),
(128, 'Nigeria', 'NG', 'NGA', 'Nigerian n', 'NGN', '₦', '234', '11', '13', NULL, NULL),
(129, 'North Macedonia', 'MK', 'MKD', 'Macedonian', 'MKD', 'ден', '389', '8', '8', NULL, NULL),
(130, 'Norway', 'NO', 'NOR', 'Norwegian ', 'NOK', 'kr', '47', '8', '8', NULL, NULL),
(131, 'Oman', 'OM', 'OMN', 'Omani rial', 'OMR', 'ر.ع.', '968', '8', '8', NULL, NULL),
(132, 'Pakistan', 'PK', 'PAK', 'Pakistani ', 'PKR', '₨', '92', '10', '12', NULL, NULL),
(133, 'Palau', 'PW', 'PLW', 'United Sta', 'USD', '$', '680', '8', '8', NULL, NULL),
(134, 'Palestine', 'PS', 'PSE', 'Israeli ne', 'ILS', '₪', '970', '9', '10', NULL, NULL),
(135, 'Panama', 'PA', 'PAN', 'Panamanian', 'PAB', 'B/.', '507', '8', '8', NULL, NULL),
(136, 'Papua New Guinea', 'PG', 'PNG', 'Papua New ', 'PGK', 'K', '675', '8', '8', NULL, NULL),
(137, 'Paraguay', 'PY', 'PRY', 'Paraguayan', 'PYG', '₲', '595', '9', '11', NULL, NULL),
(138, 'Peru', 'PE', 'PER', 'Peruvian s', 'PEN', 'S/.', '51', '10', '12', NULL, NULL),
(139, 'Philippines', 'PH', 'PHL', 'Philippine', 'PHP', '₱', '63', '10', '12', NULL, NULL),
(140, 'Poland', 'PL', 'POL', 'Polish zło', 'PLN', 'zł', '48', '9', '11', NULL, NULL),
(141, 'Portugal', 'PT', 'PRT', 'Euro', 'EUR', '€', '351', '9', '9', NULL, NULL),
(142, 'Qatar', 'QA', 'QAT', 'Qatari riy', 'QAR', 'ر.ق', '974', '8', '8', NULL, NULL),
(143, 'Romania', 'RO', 'ROU', 'Romanian l', 'RON', 'lei', '40', '9', '12', NULL, NULL),
(144, 'Russia', 'RU', 'RUS', 'Russian ru', 'RUB', '₽', '7', '10', '12', NULL, NULL),
(145, 'Rwanda', 'RW', 'RWA', 'Rwandan fr', 'RWF', 'Fr', '250', '8', '8', NULL, NULL),
(146, 'Saint Kitts and Nevis', 'KN', 'KNA', 'East Carib', 'XCD', '$', '1-869', '10', '10', NULL, NULL),
(147, 'Saint Lucia', 'LC', 'LCA', 'East Carib', 'XCD', '$', '1-758', '10', '10', NULL, NULL),
(148, 'Saint Vincent and the Grenadines', 'VC', 'VCT', 'East Carib', 'XCD', '$', '1-784', '10', '10', NULL, NULL),
(149, 'Samoa', 'WS', 'WSM', 'Samoan tāl', 'WST', 'T', '685', '8', '8', NULL, NULL),
(150, 'San Marino', 'SM', 'SMR', 'Euro', 'EUR', '€', '378', '8', '8', NULL, NULL),
(151, 'São Tomé and Príncipe', 'ST', 'STP', 'São Tomé a', 'STN', 'Db', '239', '8', '8', NULL, NULL),
(152, 'Saudi Arabia', 'SA', 'SAU', 'Saudi riya', 'SAR', 'ر.س', '966', '8', '8', NULL, NULL),
(153, 'Senegal', 'SN', 'SEN', 'West Afric', 'XOF', 'Fr', '221', '9', '9', NULL, NULL),
(154, 'Serbia', 'RS', 'SRB', 'Serbian di', 'RSD', 'дин.', '381', '8', '9', NULL, NULL),
(155, 'Seychelles', 'SC', 'SYC', 'Seychelloi', 'SCR', '₨', '248', '8', '8', NULL, NULL),
(156, 'Sierra Leone', 'SL', 'SLE', 'Sierra Leo', 'SLL', 'Le', '232', '8', '8', NULL, NULL),
(157, 'Singapore', 'SG', 'SGP', 'Singapore ', 'SGD', '$', '65', '8', '8', NULL, NULL),
(158, 'Slovakia', 'SK', 'SVK', 'Euro', 'EUR', '€', '421', '9', '9', NULL, NULL),
(159, 'Slovenia', 'SI', 'SVN', 'Euro', 'EUR', '€', '386', '8', '8', NULL, NULL),
(160, 'Solomon Islands', 'SB', 'SLB', 'Solomon Is', 'SBD', '$', '677', '8', '8', NULL, NULL),
(161, 'Somalia', 'SO', 'SOM', 'Somali shi', 'SOS', 'Sh', '252', '8', '12', NULL, NULL),
(162, 'South Africa', 'ZA', 'ZAF', 'South Afri', 'ZAR', 'R', '27', '9', '12', NULL, NULL),
(163, 'South Sudan', 'SS', 'SSD', 'South Suda', 'SSP', '£', '211', '9', '9', NULL, NULL),
(164, 'Spain', 'ES', 'ESP', 'Euro', 'EUR', '€', '34', '9', '9', NULL, NULL),
(165, 'Sri Lanka', 'LK', 'LKA', 'Sri Lankan', 'LKR', 'රු', '94', '10', '12', NULL, NULL),
(166, 'Sudan', 'SD', 'SDN', 'Sudanese p', 'SDG', '£', '249', '9', '12', NULL, NULL),
(167, 'Suriname', 'SR', 'SUR', 'Surinamese', 'SRD', '$', '597', '10', '10', NULL, NULL),
(168, 'Sweden', 'SE', 'SWE', 'Swedish kr', 'SEK', 'kr', '46', '9', '11', NULL, NULL),
(169, 'Switzerland', 'CH', 'CHE', 'Swiss fran', 'CHF', 'Fr', '41', '10', '12', NULL, NULL),
(170, 'Syria', 'SY', 'SYR', 'Syrian pou', 'SYP', '£', '963', '10', '12', NULL, NULL),
(171, 'Taiwan', 'TW', 'TWN', 'New Taiwan', 'TWD', 'NT$', '886', '10', '11', NULL, NULL),
(172, 'Tajikistan', 'TJ', 'TJK', 'Tajikistan', 'TJS', 'ЅМ', '992', '9', '9', NULL, NULL),
(173, 'Tanzania', 'TZ', 'TZA', 'Tanzanian ', 'TZS', 'Sh', '255', '10', '12', NULL, NULL),
(174, 'Thailand', 'TH', 'THA', 'Thai baht', 'THB', '฿', '66', '9', '12', NULL, NULL),
(175, 'Togo', 'TG', 'TGO', 'West Afric', 'XOF', 'Fr', '228', '8', '8', NULL, NULL),
(176, 'Tonga', 'TO', 'TON', 'Tongan paʻ', 'TOP', 'T$', '676', '8', '8', NULL, NULL),
(177, 'Trinidad and Tobago', 'TT', 'TTO', 'Trinidad a', 'TTD', '$', '1-868', '10', '10', NULL, NULL),
(178, 'Tunisia', 'TN', 'TUN', 'Tunisian d', 'TND', 'د.ت', '216', '8', '8', NULL, NULL),
(179, 'Turkey', 'TR', 'TUR', 'Turkish li', 'TRY', '₺', '90', '10', '12', NULL, NULL),
(180, 'Turkmenistan', 'TM', 'TKM', 'Turkmenist', 'TMT', 'm', '993', '8', '8', NULL, NULL),
(181, 'Tuvalu', 'TV', 'TUV', 'Australian', 'AUD', '$', '688', '8', '8', NULL, NULL),
(182, 'Uganda', 'UG', 'UGA', 'Ugandan sh', 'UGX', 'Sh', '256', '10', '12', NULL, NULL),
(183, 'Ukraine', 'UA', 'UKR', 'Ukrainian ', 'UAH', '₴', '380', '10', '12', NULL, NULL),
(184, 'United Arab Emirates', 'AE', 'ARE', 'United Ara', 'AED', 'د.إ', '971', '9', '9', NULL, NULL),
(185, 'United Kingdom', 'GB', 'GBR', 'British po', 'GBP', '£', '44', '10', '10', NULL, NULL),
(186, 'United States', 'US', 'USA', 'United Sta', 'USD', '$', '1', '10', '10', NULL, NULL),
(187, 'Uruguay', 'UY', 'URY', 'Uruguayan ', 'UYU', '$', '598', '10', '10', NULL, NULL),
(188, 'Uzbekistan', 'UZ', 'UZB', 'Uzbekistan', 'UZS', 'soʻm', '998', '9', '9', NULL, NULL),
(189, 'Vanuatu', 'VU', 'VUT', 'Vanuatu va', 'VUV', 'VT', '678', '8', '8', NULL, NULL),
(190, 'Vatican City', 'VA', 'VAT', 'Euro', 'EUR', '€', '379', '8', '8', NULL, NULL),
(191, 'Venezuela', 'VE', 'VEN', 'Venezuelan', 'VES', 'Bs.', '58', '10', '12', NULL, NULL),
(192, 'Vietnam', 'VN', 'VNM', 'Vietnamese', 'VND', '₫', '84', '10', '12', NULL, NULL),
(193, 'Yemen', 'YE', 'YEM', 'Yemeni ria', 'YER', '﷼', '967', '10', '12', NULL, NULL),
(194, 'Zambia', 'ZM', 'ZMB', 'Zambian kw', 'ZMW', 'ZK', '260', '10', '12', NULL, NULL),
(195, 'Zimbabwe', 'ZW', 'ZWE', 'United Sta', 'USD', '$', '263', '10', '12', NULL, NULL);