<?php
return [
	'success'          			=> 200,
	'created'                	=> 201,
	'accepted'               	=> 202,
	'not_modified'           	=> 304,
	'bad_request'            	=> 400,
	'unauthorized'           	=> 401,
	'payment_required'       	=> 402,
	'forbidden'              	=> 403,
	'not_found'              	=> 404,
	'method_not_allowed'     	=> 405,
	'internal_server_error'  	=> 500,
	'unprocessable_entity'   	=> 422,
	'service_unavailable'    	=> 503,
	'no_content'             	=> 204,
	'un_authorized'           	=> 401,

	// api response status code
	'not_authorized' 			=> 1000,
	'ip_address_not_allowed' 	=> 1001,
	'validation_error' 			=> 1002,
	'sender_id_not_associated' 	=> 1003,
	'dlt_template_already_exist'=> 1004,
	'exception_occur' 			=> 1005,
	'invalid_schedule_date_time'=> 1006,
	'insufficient_balance' 		=> 1007,
	'promotional_message_not_allowed_selected_time' => 1008,
	'spam_keyword_detected' 	=> 1009,
	'mobile_number_not_found' 	=> 1010,
	'dlt_template_not_associated' 	=> 1011,
	'incorrect_otp' 			=> 1012,
	'campaign_token_not_found' 	=> 1013,
	'campaign_not_found' 		=> 1014,
	'invalid_mobile_number' 	=> 1015,
	'account_inactive' 			=> 1016,
	'invalid_account_keys' 		=> 1017,
	'gateway_not_working' 		=> 1018,
	'voice_template_not_found' 	=> 1019,
	'voice_file_not_verified' 	=> 1020,
	'mobile_number_limit_exceeded' 	=> 1021,
	'voice_obd_type_not_matched' 	=> 1022,
	'wa_template_not_associated' 	=> 1031,
	'country_detail_not_found' 	=> 1032,
	'wa_charges_not_found' 	=> 1033,
	'wa_configurations_not_found' 	=> 1034,
	'mobile_number_length_invalid' => 1035,
	'country_code_not_matched' => 1036,
	'only_india_country_code_allowed' => 1037,
	'invalid_payload' => 1038,

];